spring:
#  profiles:
#    active: dev
  mail:
    host: smtp.qq.com
    username: 1829462342@qq.com
    password: ${qqmail_key}
    port: 587
    properties:
      mail:
        store:
          protocol: imap
        imap:
          host: imap.qq.com
          port: 993
          ssl:
            enable: true
          usesocketchannels: true
        smtp:
          auth: true

logging:
  level:
    root: info